function [outputArg1,outputArg2] = findCentersManual(center)
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here

ss=get(0,'ScreenSize');
sh=ss(4);
sw=ss(3);

height0=300;
width0=240;
cellHeight=25;

tolsFig=figure('Name','Center Finder','NumberTitle','off','Position',[(sw-width0)/2,(sh-height0)/2,width0,height0+80],'MenuBar','none','ToolBar','none');

uicontrol('Style', 'text', 'String', 'Enter Up to 8 Tolerances to determine the best Smooth',...
    'Position', [width0/2-100,height0+30,200,30]);

for i=1:8
uicontrol('Style', 'text', 'String', ['Tol ' num2str(i) ':'],...
    'Position', [width0/2-80,height0-i*cellHeight+25,50,cellHeight]);
end
tolboxes=struct();
tolboxes.tol1=uicontrol('Style', 'edit',...
   'Position', [width0/2-10,height0-cellHeight+32,50,cellHeight-4]);
tolboxes.tol2=uicontrol('Style', 'edit',...
   'Position', [width0/2-10,height0-2*cellHeight+32,50,cellHeight-4]);
tolboxes.tol3=uicontrol('Style', 'edit',...
   'Position', [width0/2-10,height0-3*cellHeight+32,50,cellHeight-4]);
tolboxes.tol4=uicontrol('Style', 'edit',...
   'Position', [width0/2-10,height0-4*cellHeight+32,50,cellHeight-4]);
tolboxes.tol5=uicontrol('Style', 'edit',...
   'Position', [width0/2-10,height0-5*cellHeight+32,50,cellHeight-4]);
tolboxes.tol6=uicontrol('Style', 'edit',...
   'Position', [width0/2-10,height0-6*cellHeight+32,50,cellHeight-4]);
tolboxes.tol7=uicontrol('Style', 'edit',...
   'Position', [width0/2-10,height0-7*cellHeight+32,50,cellHeight-4]);
tolboxes.tol8=uicontrol('Style', 'edit',...
   'Position', [width0/2-10,height0-8*cellHeight+32,50,cellHeight-4]);
warningText=uicontrol('Style', 'text', 'String', '',...
              'Position', [width0/2-100,75,200,45],...  
              'ForegroundColor',[1 0 0],...
              'Callback',@(src,evnt)superComp(seriesNum));

uicontrol('Style', 'pushbutton', 'String', 'Continue',...
    'Position', [10,40,220,30],...
    'Callback',@(src,evnt)loadTols);

uicontrol('Style', 'pushbutton', 'String', 'Go Back',...
    'Position', [10,10,220,30],...
    'Callback',@(src,evnt)goBack);

end

